# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-11 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_seri_number', models.IntegerField(max_length=20)),
                ('device_name', models.CharField(max_length=20)),
                ('device_os', models.CharField(choices=[('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4'), ('N5', 'N5'), ('NO', 'NO')], max_length=20)),
                ('device_quantity', models.IntegerField(default=1)),
                ('requester', models.CharField(max_length=20)),
                ('costcenter', models.CharField(max_length=20)),
                ('project', models.CharField(max_length=20)),
                ('owner', models.EmailField(max_length=254)),
                ('label', models.CharField(max_length=20)),
                ('add_date', models.DateTimeField(verbose_name='date for device addin')),
                ('device_status', models.CharField(choices=[('N1', 'N1'), ('N2', 'N2'), ('N3', 'N3'), ('N4', 'N4'), ('N5', 'N5'), ('NO', 'NO')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='order_details',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
